version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: dev-postgres-corefin
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: corefin
    ports:
      - "5432:5432" # [máquina] : [Docker]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: